version: '3.8'
services:
  db:
    container_name: mentaltext-database_1
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: holamundo
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mentaltext-network


volumes:
  cache:
    driver: local

networks:
  mentaltext-network:
